### ISSUE TITLE
Vectorize UN Open GIS logo -> SVG

### ISSUE THREAD

**Issue by albertkun** [UNopenGIS/7#233]
Currently the logo is in PNG format, which makes it hard for usage in graphics.

**Comment by hfu** [comment]
Thanks @albertkun for creating an issue. 

# What we want
UN Smart Maps Group wants vector version of UN Open GIS logo for documentation purposes. 

# Current status
The best raster file we have is the following: 

![raster un open gis logo](https://user-images.githubusercontent.com/18297/245625922-2d47efa5-13da-4a9e-a80e-443581538acd.png)

# Possible way forward
As discussed in https://github.com/UNopenGIS/smartmaps/issues/33, maybe we can have a plan to start from https://commons.wikimedia.org/wiki/File:Logo_of_the_United_Nations.svg and consult with UN Geospatial Information Section for their advice.

**Comment by albertkun** [comment]
@hfu Thank you for the image! 

Two quick questions!

1. Is the font family for `UN Open GIS` the `Futura` font?
2. Is the font family for `Initiative` or `Futura`?

**Comment by hfu** [comment]
@albertkun For the choice of font of UN Open GIS logo, we need to ask the bureau or secreatariat because I do not know documentation about that. One alternative is that we develop a vector version initially with `Future` as SMG variation because `Futura` is a standard font for SMG. And then we consult with the bureau for their advice. 

I like the latter option because we can bring something we can discuss. Thank you for the progress.

**Comment by albertkun** [comment]
@hfu Great! Thank you for your feedback! One last question, when you mentioned `Future` font above, did you mean `Futura` or is there another font called `Future` we are using? I appreciate all the input!

**Comment by hfu** [comment]
@albertkun Sorry, they all should have been `Futura`.

**Comment by albertkun** [comment]
@hfu no problem at all! I just wanted to make sure!

**Comment by hfu** [comment]
#274
