### ISSUE TITLE
Working statement

### ISSUE THREAD

**Issue by albertkun** [UNopenGIS/7#245]
"we are an international community that knows the importance of local communities"

**Comment by albertkun** [comment]
Because we are a hub, you can choose different lines

**Comment by hfu** [comment]
1. We are an international community that knows the importance of local communities. 
2. That is why we would like to function as a hub that connect local communities. 
3. The reason why we would like to expand ourselves is our nature as a hub. Scale matters for a hub. 
4. Because we are a hub, we need to provide voluntary participating opportunities to onboard new people. 
5. We have different directions and lines that connects different geography or technology areas, that is why we are a hub. 
6. Differences are the source of our strength though they sometimes are threats. Overcoming such threats is intrinsic.

**Comment by hfu** [comment]
- Smart is about people. So Smart Maps are about people.

**Comment by hfu** [comment]
#274
