### ISSUE TITLE
Facilitator of Smart Maps Meetup Monthly

### ISSUE THREAD

**Issue by hfu** [UNopenGIS/7#246]
As a result of #215, I am wondering who would be the best possible facilitator of Smart Maps Meetup Monthly. It looks like @albertkun is far more experienced facilitator because of his job in UCLA. 

@albertkun, do you think it is possible for you to take the facilitator position of the Smart Maps Meetup Pacific / Monthly. 

If so, if I may I would like to ask you to take the facilitator role from the September meetup, or further the next Meetup (#219) tomorrow. 

@albertkun what do you think?

**Comment by albertkun** [comment]
@hfu thank you for your trust in me! I don't mind being the facilitator of the monthly meeting, although I think we should announce it to the meeting tomorrow! I think starting in September would be best so that I can prepare for it! But feel to let me know what you think!

**Comment by hfu** [comment]
Thank you, @albertkun, for your prompt response. Yes, I would like to announce tomorrow that you will be assuming the role of facilitator starting from September. It seems like perfect timing, as we are set to have a guest speaker from California next month.

**Comment by albertkun** [comment]
@hfu While thinking over it a little more, what do you think of using a  co-facilitator system where there is one other person sharing the facilitation role? This could help with generating new meeting ideas and also be a backup incase one facilitator becomes busy. 

Also I'd like to clarify that what I have in my mind of being a facilitator is to set the agenda and run the meeting and not to direct the group (directing the group would be more of a group chair!). 

I think both these points are important to consider as we grow in size because I want to make sure everyone has enough capacity to sustain and contribute to the group democratically! What do you think?

**Comment by hfu** [comment]
Thank you @albertkun for the points. I agree it would be good the think in a systematic way. 

As I understand, we have differente meeting we take different roles: 

## UN Open GIS Monthly
- Lead: the Bureau (Maria, Kyoung-Soo, Ki-Joune)
- Facilitator: Ki-Joune

## UN Smart Maps Weekly
- Lead: Hidenori
- Facilitator: Hidenori

## UN Smart Maps Pacific (Monthly)
- Lead: Hidenori
- Facilitator: co-facilitating system including Albert

## UN Smart Maps Atlantic (Quarterly)
- Lead: Hidenori
- Facilitator: Timur from UNGIS

I believe that we can do some more experiments, and find a best way to have great Pacific Meetups!

**Comment by hfu** [comment]
#274
